arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
# Desactiva el paquete sintético (el causante del error de URI)
synthetic-package: false
# Define dónde quieres que se guarde el código generado
output-dir: lib/l10n
