name: myapp
description: "A Blog de notas Flutter project."
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  reorderable_grid_view: ^2.2.8
  share_plus: ^12.0.1
  image_picker: ^1.2.1
  flutter_quill: ^11.5.0
  flutter_quill_extensions: ^11.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  dynamic_color: ^1.8.1
  flutter_tts: ^4.2.5
  shared_preferences: ^2.5.4
  google_fonts: ^8.0.2
  flutter_floating_window: ^1.1.0
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icon/notas.png"
  # Opcional: para iconos adaptativos de Android
  adaptive_icon_background: "#FFFFFF" 
  adaptive_icon_foreground: "assets/icon/notas.png"
  # Configuración para Web
  web:
    generate: true
    image_path: "assets/icon/notas.png"