plugins {
    // Plugins automatically generated by MLGradleWriter.kt
    alias(libs.plugins.android.application)
    id("com.google.devtools.ksp")
}

android {
    namespace = "com.Jhon.myempty.blogdenotasjava"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.Jhon.myempty.blogdenotasjava"
        minSdk = 23
        targetSdk = 36
        versionCode = 1100
        versionName = "1.10.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

dependencies {
    implementation(libs.androidx.core)
    implementation(libs.androidx.appcompat)
    implementation(libs.material)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.cardview)
    implementation(libs.androidx.documentfile)
    implementation(libs.androidx.recyclerview)
    implementation("com.github.bumptech.glide:glide:5.0.5")
    // Use KSP for Glide 5.x annotation processing
    ksp("com.github.bumptech.glide:ksp:5.0.5")
}